version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: qldsv_htc_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123456
    volumes:
      - ./sql:/usr/config/sql
      - ./docker-db-init.sh:/usr/config/docker-db-init.sh
    entrypoint: /bin/bash -c "chmod +x /usr/config/docker-db-init.sh && /usr/config/docker-db-init.sh & /opt/mssql/bin/sqlservr"
    restart: unless-stopped
