USE QLDSV_HTC;
SET DATEFORMAT ymd;

-- 1. Xóa dữ liệu đăng ký và lớp tín chỉ cũ
DELETE FROM DANGKY;
DELETE FROM LOPTINCHI;
DELETE FROM SINHVIEN;

DBCC CHECKIDENT ('LOPTINCHI', RESEED, 0);

-- 2. Sinh viên: Tạo 25 SV cho N20DCCN01 (Khóa 2020-2025, đã tốt nghiệp)
DECLARE @i INT = 1;
DECLARE @masv VARCHAR(10);
DECLARE @ho NVARCHAR(50);
DECLARE @ten NVARCHAR(10);
DECLARE @phai BIT;

WHILE @i <= 25
BEGIN
    SET @masv = 'N20CN' + RIGHT('0000' + CAST(@i AS VARCHAR(4)), 4);
    SET @ten = CHOOSE(@i % 10 + 1, N'An', N'Bình', N'Cường', N'Dũng', N'Giang', N'Hải', N'Khánh', N'Linh', N'Minh', N'Nam');
    SET @ho = CHOOSE(@i % 5 + 1, N'Nguyễn Văn', N'Trần Minh', N'Lê Hoàng', N'Phạm Quốc', N'Vũ Đức');
    SET @phai = CASE WHEN @i % 3 = 0 THEN 1 ELSE 0 END;
    
    INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD)
    VALUES (@masv, @ho, @ten, @phai, N'TP. Hồ Chí Minh', '2002-05-15', 'N20DCCN01', 0, '123456');
    
    SET @i = @i + 1;
END;

-- Sinh viên: Tạo 25 SV cho N21DCCN01 (Khóa 2021-2026, năm cuối)
SET @i = 1;
WHILE @i <= 25
BEGIN
    SET @masv = 'N21CN' + RIGHT('0000' + CAST(@i AS VARCHAR(4)), 4);
    SET @ten = CHOOSE(@i % 10 + 1, N'Phương', N'Quốc', N'Sơn', N'Trang', N'Tuấn', N'Vinh', N'Xuân', N'Yến', N'Anh', N'Bích');
    SET @ho = CHOOSE(@i % 5 + 1, N'Nguyễn Thị', N'Trần Văn', N'Lê Thị', N'Phạm Minh', N'Hoàng Kim');
    SET @phai = CASE WHEN @i % 2 = 0 THEN 1 ELSE 0 END;
    
    INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD)
    VALUES (@masv, @ho, @ten, @phai, N'Hà Nội', '2003-08-20', 'N21DCCN01', 0, '123456');
    
    SET @i = @i + 1;
END;

-- Sinh viên: Tạo 25 SV cho N22DCCN01 (Khóa 2022-2027, đang học)
SET @i = 1;
WHILE @i <= 25
BEGIN
    SET @masv = 'N22CN' + RIGHT('0000' + CAST(@i AS VARCHAR(4)), 4);
    SET @ten = CHOOSE(@i % 10 + 1, N'Huy', N'Khoa', N'Lâm', N'Mai', N'Ngọc', N'Oanh', N'Phúc', N'Quang', N'Thảo', N'Uy');
    SET @ho = CHOOSE(@i % 5 + 1, N'Nguyễn Anh', N'Trần Quốc', N'Lê Hồng', N'Phạm Tiến', N'Đỗ Hoài');
    SET @phai = CASE WHEN @i % 4 = 0 THEN 1 ELSE 0 END;
    
    INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD)
    VALUES (@masv, @ho, @ten, @phai, N'Cần Thơ', '2004-11-12', 'N22DCCN01', 0, '123456');
    
    SET @i = @i + 1;
END;

-- Sinh viên: Các lớp khác để giữ số liệu demo
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N20VT0001', N'Trịnh Văn', N'Bảo', 0, N'TP.HCM', '20020220', 'N20DCVT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N20VT0002', N'Nguyễn Thị', N'Cúc', 1, N'Hà Nội', '20020610', 'N20DCVT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N21VT0001', N'Phạm Hoàng', N'Duy', 0, N'TP.HCM', '20030405', 'N21DCVT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N22VT0001', N'Võ Tấn', N'Khoa', 0, N'TP.HCM', '20040130', 'N22DCVT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N21KT0001', N'Hồ Văn', N'Nam', 0, N'TP.HCM', '20030708', 'N21DCKT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N22KT0001', N'Lê Quốc', N'Phúc', 0, N'TP.HCM', '20040517', 'N22DCKT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N21CK0001', N'Cao Minh', N'Sơn', 0, N'TP.HCM', '20030303', 'N21DCCK01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, DIACHI, NGAYSINH, MALOP, DANGHIHOC, PASSWORD) VALUES('N22CK0001', N'Bùi Văn', N'Ước', 0, N'TP.HCM', '20040625', 'N22DCCK01', 0, '123456');

-- 3. Tạo Lớp Tín Chỉ (LOPTINCHI) cho các năm học học kỳ
-- Chúng ta sẽ mở các LTC cho CNTT, và một số cho VT/KT/CK
-- Niên khóa: 2020-2021 đến 2025-2026. Mỗi kỳ mở 4-6 môn.
-- Table Seed: LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA)

-- K20 (2020-2021 đến 2023-2024)
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 1, 'BAS1150', 1, 'GV01', 'CNTT', 10, 0, 40); -- Triết
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 1, 'BAS1201', 1, 'GV02', 'CNTT', 10, 0, 40); -- Đại số
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 1, 'INT1154', 1, 'GV03', 'CNTT', 10, 0, 40); -- Tin học CS1
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 1, 'BAS1106', 1, 'GV01', 'CNTT', 10, 0, 40); -- Thể chất 1

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 2, 'BAS1151', 1, 'GV05', 'CNTT', 10, 0, 40); -- Kinh tế chính trị
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 2, 'BAS1203', 1, 'GV06', 'CNTT', 10, 0, 40); -- Giải tích 1
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 2, 'INT1155', 1, 'GV07', 'CNTT', 10, 0, 40); -- Tin học CS2
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2020-2021', 2, 'BAS1107', 1, 'GV08', 'CNTT', 10, 0, 40); -- Thể chất 2

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 1, 'BAS1122', 1, 'GV01', 'CNTT', 10, 0, 40); -- Tư tưởng HCM
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 1, 'BAS1204', 1, 'GV02', 'CNTT', 10, 0, 40); -- Giải tích 2
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 1, 'INT1306', 1, 'GV03', 'CNTT', 10, 0, 40); -- CTDL & GT
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 1, 'SKD1101', 1, 'GV05', 'CNTT', 10, 0, 40); -- Thuyết trình

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 2, 'BAS1152', 1, 'GV06', 'CNTT', 10, 0, 40); -- CNXHKH
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 2, 'BAS1226', 1, 'GV07', 'CNTT', 10, 0, 40); -- Xác suất TK
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 2, 'INT1313', 1, 'GV08', 'CNTT', 10, 0, 40); -- CSDL
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2021-2022', 2, 'SKD1102', 1, 'GV01', 'CNTT', 10, 0, 40); -- Làm việc nhóm

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 1, 'BAS1153', 1, 'GV02', 'CNTT', 10, 0, 40); -- Lịch sử Đảng
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 1, 'INT1336', 1, 'GV03', 'CNTT', 10, 0, 40); -- Mạng máy tính
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 1, 'INT13145', 1, 'GV05', 'CNTT', 10, 0, 40); -- Kiến trúc máy tính
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 1, 'SKD1103', 1, 'GV06', 'CNTT', 10, 0, 40); -- Tạo lập văn bản

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 2, 'INT1341', 1, 'GV07', 'CNTT', 10, 0, 40); -- Nhập môn AI
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 2, 'ELE1309', 1, 'GV08', 'CNTT', 10, 0, 40); -- Điện tử số
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2022-2023', 2, 'OTC1301', 1, 'GV01', 'CNTT', 10, 0, 40); -- Thực hành cơ sở

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2023-2024', 1, 'ELE1415', 1, 'GV02', 'CNTT', 10, 0, 40); -- Hệ thống nhúng
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2023-2024', 1, 'INT13146', 1, 'GV03', 'CNTT', 10, 0, 40); -- Xử lý ảnh
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2023-2024', 1, 'SKD1105', 1, 'GV05', 'CNTT', 10, 0, 40); -- Giao tiếp

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2023-2024', 2, 'ELE1401', 1, 'GV06', 'CNTT', 10, 0, 40); -- CAD/CAM
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2023-2024', 2, 'ELE1422', 1, 'GV07', 'CNTT', 10, 0, 40); -- Thị giác máy tính
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2023-2024', 2, 'SKD1108', 1, 'GV08', 'CNTT', 10, 0, 40); -- NCKH

-- K21 (2021-2022 đến 2024-2025)
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2024-2025', 1, 'ELE1415', 2, 'GV02', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2024-2025', 1, 'INT13146', 2, 'GV03', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2024-2025', 1, 'SKD1105', 2, 'GV05', 'CNTT', 10, 0, 40);

INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2024-2025', 2, 'ELE1401', 2, 'GV06', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2024-2025', 2, 'ELE1422', 2, 'GV07', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2024-2025', 2, 'SKD1108', 2, 'GV08', 'CNTT', 10, 0, 40);

-- K22 (2022-2023 đến 2025-2026 - Học kỳ hiện tại)
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2025-2026', 1, 'BAS1153', 2, 'GV02', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2025-2026', 1, 'INT1336', 2, 'GV03', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2025-2026', 1, 'INT13145', 2, 'GV05', 'CNTT', 10, 0, 40);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP, SOSVTOIDA) VALUES('2025-2026', 1, 'SKD1103', 2, 'GV06', 'CNTT', 10, 0, 40);

-- 4. Đăng ký & Nhập điểm (DANGKY)
-- Học sinh N20DCCN01 (tất cả 25 SV) học 29 lớp tín chỉ của K20 (mã LTC từ 1 đến 29)
-- Chúng ta gán điểm ngẫu nhiên thực tế (Giỏi, Khá, TB, Yếu, Rớt) cho từng SV

-- Sử dụng cursor để sinh tự động điểm ngẫu nhiên đẹp đẽ
DECLARE @sv_idx INT;
DECLARE @ltc_idx INT;
DECLARE @masv_curr VARCHAR(10);
DECLARE @diem_cc FLOAT;
DECLARE @diem_gk FLOAT;
DECLARE @diem_ck FLOAT;
DECLARE @rand_val FLOAT;

-- Tạo điểm cho K20 (LTC 1 đến 29)
SET @sv_idx = 1;
WHILE @sv_idx <= 25
BEGIN
    SET @masv_curr = 'N20CN' + RIGHT('0000' + CAST(@sv_idx AS VARCHAR(4)), 4);
    
    SET @ltc_idx = 1;
    WHILE @ltc_idx <= 29
    BEGIN
        -- Sinh điểm ngẫu nhiên có quy luật
        SET @rand_val = RAND(CHECKSUM(NEWID()));
        
        SET @diem_cc = 7.0 + ROUND(@rand_val * 3.0, 0); -- 7 đến 10
        SET @diem_gk = 4.0 + ROUND(@rand_val * 6.0, 1); -- 4 đến 10
        SET @diem_ck = 3.5 + ROUND(RAND(CHECKSUM(NEWID())) * 6.5, 1); -- 3.5 đến 10

        -- Thỉnh thoảng có vài SV rớt (điểm CK < 4.0)
        IF (@sv_idx % 7 = 0 AND @ltc_idx % 5 = 0)
        BEGIN
            SET @diem_ck = 2.0 + ROUND(RAND(CHECKSUM(NEWID())) * 1.5, 1); -- 2.0 đến 3.5 (Rớt)
        END

        INSERT INTO DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@ltc_idx, @masv_curr, @diem_cc, @diem_gk, @diem_ck, 0);
        
        SET @ltc_idx = @ltc_idx + 1;
    END;
    SET @sv_idx = @sv_idx + 1;
END;

-- Tạo điểm cho K21 (Học từ năm 2021 đến 2024)
SET @sv_idx = 1;
WHILE @sv_idx <= 25
BEGIN
    SET @masv_curr = 'N21CN' + RIGHT('0000' + CAST(@sv_idx AS VARCHAR(4)), 4);
    
    -- Danh sách LTC cho K21 học (LTC 1 đến 23, cộng thêm các LTC 30 đến 35)
    SET @ltc_idx = 1;
    WHILE @ltc_idx <= 23
    BEGIN
        SET @rand_val = RAND(CHECKSUM(NEWID()));
        SET @diem_cc = 7.0 + ROUND(@rand_val * 3.0, 0);
        SET @diem_gk = 5.0 + ROUND(@rand_val * 5.0, 1);
        SET @diem_ck = 4.0 + ROUND(RAND(CHECKSUM(NEWID())) * 6.0, 1);
        
        INSERT INTO DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@ltc_idx, @masv_curr, @diem_cc, @diem_gk, @diem_ck, 0);
        
        SET @ltc_idx = @ltc_idx + 1;
    END;

    -- LTC 30 đến 32 (đã có điểm)
    SET @ltc_idx = 30;
    WHILE @ltc_idx <= 32
    BEGIN
        SET @rand_val = RAND(CHECKSUM(NEWID()));
        SET @diem_cc = 7.0 + ROUND(@rand_val * 3.0, 0);
        SET @diem_gk = 5.0 + ROUND(@rand_val * 5.0, 1);
        SET @diem_ck = 4.0 + ROUND(RAND(CHECKSUM(NEWID())) * 6.0, 1);
        
        INSERT INTO DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@ltc_idx, @masv_curr, @diem_cc, @diem_gk, @diem_ck, 0);
        
        SET @ltc_idx = @ltc_idx + 1;
    END;

    -- LTC 33 đến 35 (đang học, điểm null)
    SET @ltc_idx = 33;
    WHILE @ltc_idx <= 35
    BEGIN
        INSERT INTO DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@ltc_idx, @masv_curr, NULL, NULL, NULL, 0);
        
        SET @ltc_idx = @ltc_idx + 1;
    END;
    
    SET @sv_idx = @sv_idx + 1;
END;

-- Tạo điểm cho K22 (Học kì 2025-2026 kì 1, LTC 36-39)
-- K22 chỉ có điểm học kỳ trước, kỳ 2025-2026 kì 1 (LTC 36, 37, 38, 39) chưa có điểm
SET @sv_idx = 1;
WHILE @sv_idx <= 25
BEGIN
    SET @masv_curr = 'N22CN' + RIGHT('0000' + CAST(@sv_idx AS VARCHAR(4)), 4);
    
    -- Đăng ký các LTC kỳ trước (LTC 1-15)
    SET @ltc_idx = 1;
    WHILE @ltc_idx <= 15
    BEGIN
        SET @rand_val = RAND(CHECKSUM(NEWID()));
        SET @diem_cc = 8.0 + ROUND(@rand_val * 2.0, 0);
        SET @diem_gk = 5.0 + ROUND(@rand_val * 5.0, 1);
        SET @diem_ck = 4.5 + ROUND(RAND(CHECKSUM(NEWID())) * 5.5, 1);
        
        INSERT INTO DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@ltc_idx, @masv_curr, @diem_cc, @diem_gk, @diem_ck, 0);
        
        SET @ltc_idx = @ltc_idx + 1;
    END;
    
    -- Đăng ký học kỳ hiện tại (chưa có điểm)
    SET @ltc_idx = 36;
    WHILE @ltc_idx <= 39
    BEGIN
        INSERT INTO DANGKY (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK, HUYDANGKY)
        VALUES (@ltc_idx, @masv_curr, NULL, NULL, NULL, 0);
        SET @ltc_idx = @ltc_idx + 1;
    END;
    
    SET @sv_idx = @sv_idx + 1;
END;

PRINT N'Successfully generated full dataset for K20, K21, K22 with realistic grade distributions!';
