-- Thêm dữ liệu để phân trang hoạt động (>8 dòng mỗi bảng)
USE QLDSV_HTC;

-- Thêm 2 khoa mới
INSERT INTO KHOA (MAKHOA, TENKHOA) VALUES ('KT', N'Kế toán');
INSERT INTO KHOA (MAKHOA, TENKHOA) VALUES ('CK', N'Cơ khí');

-- Thêm 6 lớp mới (tổng 15 lớp)
INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) VALUES ('D17CQCP01', N'Công nghệ phần mềm 2017', '2017-2021', 'CNTT');
INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) VALUES ('D17CQMT01', N'Mạng máy tính 2017', '2017-2021', 'CNTT');
INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) VALUES ('D16CQKT01', N'Kế toán 2016', '2016-2020', 'KT');
INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) VALUES ('D17CQKT01', N'Kế toán 2017', '2017-2021', 'KT');
INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) VALUES ('D16CQCK01', N'Cơ khí 2016', '2016-2020', 'CK');
INSERT INTO LOP (MALOP, TENLOP, KHOAHOC, MAKHOA) VALUES ('D17CQCK01', N'Cơ khí 2017', '2017-2021', 'CK');

-- Thêm 8 giảng viên mới (tổng 14 GV)
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV07', N'Trần Văn', N'Hùng', N'Thạc sĩ', N'', N'Lập trình', 'CNTT');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV08', N'Phạm Thị', N'Lan', N'Tiến sĩ', N'PGS', N'Cơ sở dữ liệu', 'CNTT');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV09', N'Lê Minh', N'Tuấn', N'Thạc sĩ', N'', N'An ninh mạng', 'VT');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV10', N'Ngô Thanh', N'Bình', N'Tiến sĩ', N'', N'Trí tuệ nhân tạo', 'VT');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV11', N'Đỗ Văn', N'Long', N'Thạc sĩ', N'', N'Kế toán tài chính', 'KT');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV12', N'Vũ Thị', N'Hương', N'Tiến sĩ', N'PGS', N'Kiểm toán', 'KT');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV13', N'Bùi Quang', N'Đức', N'Thạc sĩ', N'', N'Cơ khí chế tạo', 'CK');
INSERT INTO GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA) VALUES ('GV14', N'Hoàng Thị', N'Mai', N'Tiến sĩ', N'', N'Tự động hóa', 'CK');

-- Thêm 5 môn học mới (tổng 12 môn)
INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) VALUES ('CSDL', N'Cơ sở dữ liệu', 30, 30);
INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) VALUES ('LTJV', N'Lập trình Java', 30, 30);
INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) VALUES ('TTHCM', N'Tư tưởng HCM', 30, 0);
INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) VALUES ('KTCT', N'Kế toán chi tiết', 45, 15);
INSERT INTO MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH) VALUES ('VLDC', N'Vật lý đại cương', 45, 15);

-- Thêm 20 sinh viên mới (tổng 33 SV)
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCN001', N'Nguyễn Văn', N'An', 0, '2000-03-15', N'TP.HCM', 'D17CQCP01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCN002', N'Trần Thị', N'Bích', 1, '2000-07-22', N'Bình Dương', 'D17CQCP01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCN003', N'Lê Hoàng', N'Cường', 0, '1999-11-05', N'Đồng Nai', 'D17CQCP01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCN004', N'Phạm Minh', N'Đức', 0, '2000-01-18', N'TP.HCM', 'D17CQMT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCN005', N'Võ Thị', N'Em', 1, '2000-09-30', N'Long An', 'D17CQMT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCKT001', N'Hoàng Văn', N'Phú', 0, '1999-04-12', N'TP.HCM', 'D16CQKT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCKT002', N'Đặng Thị', N'Giang', 1, '1999-08-25', N'Hà Nội', 'D16CQKT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCKT001', N'Bùi Thanh', N'Hải', 0, '2000-02-14', N'TP.HCM', 'D17CQKT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCKT002', N'Ngô Thị', N'Ích', 1, '2000-06-07', N'Cần Thơ', 'D17CQKT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCCK001', N'Trương Văn', N'Kiệt', 0, '1999-12-01', N'TP.HCM', 'D16CQCK01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCCK002', N'Lý Thị', N'Liên', 1, '1999-05-19', N'Đà Nẵng', 'D16CQCK01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCK001', N'Mai Quốc', N'Minh', 0, '2000-10-08', N'TP.HCM', 'D17CQCK01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N17DCCK002', N'Phan Thị', N'Ngọc', 1, '2000-04-22', N'Vũng Tàu', 'D17CQCK01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N15DCCN006', N'Đinh Công', N'Phong', 0, '1998-08-11', N'TP.HCM', 'D15CQCP01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N15DCCN007', N'Cao Thị', N'Quỳnh', 1, '1998-12-29', N'Bình Phước', 'D15CQMT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCCN006', N'Tạ Minh', N'Sang', 0, '1999-03-07', N'TP.HCM', 'D16CQCP01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCCN007', N'Dương Thị', N'Trang', 1, '1999-07-16', N'Tiền Giang', 'D16CQIS01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCCN008', N'Huỳnh Tấn', N'Uy', 0, '1999-01-23', N'TP.HCM', 'D16CQMT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N15DCVT001', N'Lâm Văn', N'Vinh', 0, '1998-06-14', N'TP.HCM', 'D15CQVT01', 0, '123456');
INSERT INTO SINHVIEN (MASV, HO, TEN, PHAI, NGAYSINH, DIACHI, MALOP, DANGHIHOC, PASSWORD) VALUES ('N16DCVT001', N'Đoàn Thị', N'Xuân', 1, '1999-09-03', N'Kiên Giang', 'D16CQVT01', 0, '123456');

-- Thêm 8 lớp tín chỉ mới (tổng 15 LTC)
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2016-2017', 1, 'CSDL', 1, 'GV08', 'CNTT', 20, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2016-2017', 1, 'LTJV', 1, 'GV07', 'CNTT', 20, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2016-2017', 2, 'MMT', 1, 'GV03', 'CNTT', 15, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2017-2018', 1, 'CTDL', 1, 'GV01', 'CNTT', 20, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2017-2018', 1, 'AV', 1, 'GV09', 'VT', 25, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2017-2018', 2, 'KTCT', 1, 'GV11', 'KT', 15, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2017-2018', 2, 'VLDC', 1, 'GV13', 'CK', 15, 0);
INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP) VALUES ('2016-2017', 2, 'TTHCM', 1, 'GV10', 'VT', 30, 0);

PRINT 'Done - added data for pagination testing';
