-- Thêm cột SOSVTOIDA (sĩ số tối đa) vào bảng LOPTINCHI
-- Chạy 1 lần nếu cột chưa tồn tại

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME='LOPTINCHI' AND COLUMN_NAME='SOSVTOIDA'
)
BEGIN
    ALTER TABLE LOPTINCHI ADD SOSVTOIDA int NOT NULL DEFAULT 40;
    PRINT N'Đã thêm cột SOSVTOIDA vào LOPTINCHI';
END
ELSE
BEGIN
    PRINT N'Cột SOSVTOIDA đã tồn tại';
END
GO
