-- Thêm deadline đăng ký + Lý do hủy lớp vào LOPTINCHI
-- Chạy 1 lần nếu chưa có

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME='LOPTINCHI' AND COLUMN_NAME='NGAYBATDAU_DK'
)
BEGIN
    ALTER TABLE LOPTINCHI ADD 
        NGAYBATDAU_DK date NULL,
        NGAYKETTHUC_DK date NULL,
        NGAYHETHAN_HUY date NULL,
        LYDOHUY nvarchar(200) NULL;
    
    -- Set default deadline cho LTC hiện có
    UPDATE LOPTINCHI SET 
        NGAYBATDAU_DK = '2026-07-15',
        NGAYKETTHUC_DK = '2026-07-30',
        NGAYHETHAN_HUY = '2026-07-30';
    
    PRINT N'Đã thêm cột deadline + lý do hủy';
END
ELSE
BEGIN
    PRINT N'Cột deadline đã tồn tại';
END
GO

-- Thêm SOSVTOIDA nếu chưa có
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME='LOPTINCHI' AND COLUMN_NAME='SOSVTOIDA'
)
BEGIN
    ALTER TABLE LOPTINCHI ADD SOSVTOIDA int NOT NULL DEFAULT 40;
    PRINT N'Đã thêm cột SOSVTOIDA';
END
GO
